### ISSUE TITLE
希望增加多编码支持（UTF-8, Unicode 等) 

### ISSUE THREAD

**Issue by cuixiping** [CuteLeon/Notepad#1]
我很喜欢这个记事本，解决了windows记事本无法识别unix换行符的问题。但是发现打开UTF-8编码的文件是乱码，希望还能再更新一下。

**Comment by CuteLeon** [comment]
1.sorry, 这个仓库的代码版权并不属于我，也不是我开发的。我很早之前上传代码过来仅仅是留存和分享目的，但因为疏忽而忘记标注。
2.目前暂时未找到原作者的联系方式，但原作者已在代码内声明：
`本软件是共享软件，不设版权，欢迎使用。但请不要用作商业目的，否则由此引起的一切后果自`
3.如果需要的话，请自行fork并修改；

**Comment by cuixiping** [comment]
感谢回复。不过我暂时还不懂 vb.net 开发。还能够找到原出处或者原作者吗？
